max_width = 100
reorder_imports = true
reorder_modules = true

# == Nightly only. ==
comment_width = 80
format_strings = true
group_imports = "One"
imports_indent = "Block"
imports_layout = "Mixed"
imports_granularity = "One"
reorder_impl_items = false
wrap_comments = true
