name: Dismiss Stale PR Reviews

on:
  pull_request:
    types: [
      opened,
      synchronize,
      reopened,
    ]

permissions:
  actions: read
  contents: read
  pull-requests: write

jobs:
  dismiss_stale_approvals:
    runs-on: ubuntu-latest
    steps:
      - name: Dump GitHub context
        run: |
          echo "Author Association: ${{ github.event.pull_request.author_association }}"
          echo "Full Event Payload:"
          echo "${{ toJSON(github.event) }}"

      - name: Dismiss Stale PR Reviews
        if: ${{ !contains('OWNER,MEMBER,COLLABORATOR', github.event.pull_request.author_association) }}
        uses: withgraphite/dismiss-stale-approvals@main
        with:
          github-token: ${{ secrets.GITHUB_TOKEN }}
