name: Release NPM package

on:
  workflow_dispatch:
  push:
    branches: [ main ]

jobs:
  release:
    name: NPM package
    runs-on: ubuntu-latest
    steps:
      - name: Git Checkout
        uses: actions/checkout@v4

      - name: Setup Environment
        uses: ./.github/actions/setup

      - name: Build Client JS
        run: pnpm clients:js:build

      - name: Create release PR or publish to npm
        uses: changesets/action@v1
        with:
          publish: pnpm changeset publish
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NPM_TOKEN: ${{ secrets.SOLANA_PROGRAM_NPM_TOKEN }}
